#!/usr/bin/env bash
# Installs and configures Nginx to serve "Holberton School" on port 80

sudo apt-get update -y
sudo apt-get install -y nginx

# Ensure nginx is running
sudo service nginx start

# Configure the default page
echo "Holberton School for the win!" | sudo tee /var/www/html/index.html > /dev/null

# Restart nginx
sudo service nginx restart
