#!/usr/bin/env bash
# Install nginx and configure redirect

sudo apt-get update -y
sudo apt-get install -y nginx

# Start nginx
sudo service nginx start

# Configure default page
echo "Holberton School for the win!" | sudo tee /var/www/html/index.html

# Add redirect
sudo sed -i '/server_name _;/a location /redirect_me {\n\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n}' /etc/nginx/sites-available/default

# Restart nginx
sudo service nginx restart
